# Generated by Django 2.1.4 on 2018-12-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
